### ISSUE TITLE
A minor bug on evaluation codes

### ISSUE THREAD

**Issue by liuyuan-pal** [magicleap/SuperGluePretrainedNetwork#57] opened 2021-02-05 04:03 UTC
Thanks for sharing this great work!

I find a minor bug in the evaluation code.
The results are first stored in different files named by filenames of corresponding image files.
But different sequences may have image files with the same filename, so they may overwrite each other.

Actually, the performance is almost the same with or without the bug.

**Comment by Skydes** [comment] 2021-02-05 08:54
Thanks for reporting this. Do you have some specific numbers that show the difference? For which dataset is this happening?

The results reported in the paper were computed with a different code base that certainly does not have this bug.

**Comment by liuyuan-pal** [comment] 2021-02-05 10:39
It occurs when I'm evaluating the ScanNet dataset.
It brings about 0.5% difference on all metrics, which may also be caused by different seeds of RANSAC, so I think the results are almost the same.

**Comment by liuyuan-pal** [comment] 2021-02-05 15:53
I have double-checked that there are 1500 pairs having the same filename in ScanNet. 
For example, https://github.com/magicleap/SuperGluePretrainedNetwork/blob/c0626d58c843ee0464b0fa1dd4de4059bfae0ab4/assets/scannet_test_pairs_with_gt.txt#L41 and https://github.com/magicleap/SuperGluePretrainedNetwork/blob/c0626d58c843ee0464b0fa1dd4de4059bfae0ab4/assets/scannet_test_pairs_with_gt.txt#L26

It's indeed very hard to find this bug. 
I was trying to incorporate SuperGlue in my codes. 
When I was evaluating SuperGlue using my codes to check the correctness, I always get a similar but not exactly the same result. 
Then, I checked it line by line and finally find it.
Though the performance is almost the same, I think it would be better to let you know that. :)

**Comment by angshine** [comment] 2021-02-05 16:03
I met the same problem when evaluating on ScanNet, and it's indeed caused by overwriting of part of the records, which leads to less than 1500 records when calculating the final pose AUC.

**Comment by Skydes** [comment] 2021-02-05 17:25
Ok that makes sense, I'll see if I can get a fix merged. Thanks for confirming.

**Closed** 2021-02-06 02:14 UTC
